### PR TITLE
open_cancel_scope → CancelScope

### PR DESCRIPTION
**Pull request by smurfix**

### CODE REVIEW

**Comment by njsmith** [comment]
Also you seem to have universal test failure due to warnings about `open_cancel_scope` being deprecated... did you miss some?

**Comment by smurfix** [comment]
Nope. Some other code still uses them. I assume that it's pytest-trio's fault, as it hasn't seen a release lately.

**Comment by pquentin** [comment]
Let's see if the pytest-trio release helps.

**Comment by pquentin** [comment]
The failing tests use pytest-trio 0.5.1 instead of 0.5.2: I don't know why.

**Comment by smurfix** [comment]
@pquentin because 0.5.2 wasn't released when they ran.

**Comment by njsmith** [comment]
@smurfix I think you just merged with the wrong trio versions everywhere?

**Pull request merged**
