### PR TITLE
Release v0.10.1

### PR DESCRIPTION
**Pull request by ProvoK**
Hi @smurfix @pquentin 
I'm trying to help with releasing the new version :) 
The "towncrier" utility seems not to be used since v0.8.1 (not at v0.10.0) so che generated history is not correct and I've updated it manually. 
I'm not sure it's the correct approach: I'm afraid the issue will came out again the next time towncrier will be used.

Tell me if something is missing

### CODE REVIEW

**Comment by pquentin** [comment]
Thanks!

It would be nice to get back into a clean towncrier state. It looks like you did most of the work by generating the history by hand, maybe the only thing left to do is to remove the newsfragments files?

**Comment by ProvoK** [comment]
Done! I wasn't sure that they needed to be deleted


> Thanks!
> 
> It would be nice to get back into a clean towncrier state. It looks like you did most of the work by generating the history by hand, maybe the only thing left to do is to remove the newsfragments files?

**Comment by pquentin** [comment]
Thanks. Now let's look at CI. There are two required builds that don't pass:

There's an issue with the history:

/home/travis/build/python-trio/trio-asyncio/docs/source/history.rst:15:Unexpected section title.

And an issue with 3.7-dev in Travis.

**Comment by pquentin** [comment]
(I realize the 3.7-dev failure is not your fault but we want to understand what's going on.)

**Comment by ProvoK** [comment]
I'm losing myself trying to fix older "newsfragments" (v0.9.0) that apparently were sphinx-invalid.
I've not experience with Sphinx, it might take a while...

Also, literally no idea why 3.7-dev is failing. Is there a way to rerun a master pipeline/ci?

**Comment by ProvoK** [comment]
@pquentin I've fixed the documentation. For the others failing things, honestly, I don't have that amount of time to investigate them.

It's obviously something that changed in these 5months (latest master pipeline used 3.7.2 whilst this PR pipelines are using 3.7.4rc2).

There were a [lot of changes](https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-4-release-candidate-2).

Just for the sake of argument: is it a good strategy to **require** compatibility with dev versions of python?

**Comment by pquentin** [comment]
Thank you for you work! It will definitely be helpful for the release. I also realize that what's left is not a reasonable amount of work for a first-time contributor.

I don't use trio-asyncio myself and never worked on it, so I don't know what's acceptable or not. I do know that the 3.7-dev will soon be the latest Python 3.7 version and at that point it won't be a dev version anymore.

@njsmith @smurfix thoughts?

**Comment by smurfix** [comment]
I agree -- thanks for the work so far. I'll try to find time to clean up the package …

**Comment by smurfix** [comment]
In "next" branch

**Pull request closed without merging**
